name: Publish
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # normal release
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+" # release candidate
      - "[0-9]+.[0-9]+.[0-9]+[ab][0-9]+" # alpha or beta release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set version from tag
        run: uv version ${GITHUB_REF/refs\/tags\/}
      - name: Build package
        run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  pypi-publish:
    name: Upload release to PyPI
    needs: build
    environment: publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
      name: Create GitHub release
      needs: pypi-publish
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - uses: actions/checkout@v5
      - id: changelog
        uses: agronholm/release-notes@v1
        with:
          path: CHANGELOG.md
          version_pattern: ^\#\# ([0-9][^*]*)\n
      - uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
