name: Publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # normal release
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+" # release candidate
      - "v[0-9]+.[0-9]+.[0-9]+[ab][0-9]+" # alpha or beta release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set version from tag
        run: uv version ${GITHUB_REF/refs\/tags\/v/}
      - name: Build package
        run: uv build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

  pypi-publish:
    needs: ['build']
    environment: 'publish'

    name: upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: artifact/
